 version: 2.1
 orbs:
  codecov: codecov/codecov@1.0.2

 jobs:
   build:
     docker:
       - image: circleci/node:8.12.0
     steps:
       - checkout
       #- run: npm run test:coverage
       #- codecov/upload:
          #file: {{ coverage_report_filepath }}
