 version: 2.1
 orbs:
  codecov: codecov/codecov@1.0.5

 jobs:
   build:
     docker:
       - image: circleci/node:8.12.0
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
         key: dependency-cache-{{ checksum "package-lock.json" }}
       - run: npm run test:coverage
       - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
       #- codecov/upload:
          #file: {{ coverage_report_filepath }}
