 version: 2.1
 orbs:
  codecov: codecov/codecov@1.0.5

 jobs:
   build:
     docker:
       - image: circleci/node:12.14.1
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - run:
          name: 'core-tests'
          command: 'npm run test:coverage'
       - codecov/upload:
           file: 'coverage/lcov.info'
           flags: 'core'
           conf: 'codecov.yml'
       - run:
          name: 'run-website-tests'
          command: 'cd website && npm run test:coverage'
       - codecov/upload:
           file: 'website/coverage/lcov.info'
           flags: 'website'
           conf: 'codecov.yml'
       - run:
          name: 'run-raven-tests'
          command: 'cd raven && npm run test:coverage'
       - codecov/upload:
           file: 'raven/coverage/lcov.info'
           flags: 'raven'
           conf: 'codecov.yml'
       - run:
          name: 'run-unit-tests'
          command: 'npm run test:unit-tests:coverage'
       - codecov/upload:
           file: 'coverage/unitTests/lcov.info'
           flags: 'raven'
           conf: 'codecov.yml'
